on: [push, pull_request]

name: Docker-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@master
     - name: Build the Docker image
       run: docker build . --file Dockerfile
